### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website-cms#2]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [x] [cms_status_message](https://github.com/OCA/website-cms/tree/9.0/cms_status_message) [  @TDu ][ #23 ]
- [x] [cms_form](https://github.com/OCA/website-cms/tree/9.0/cms_form) [@simahawk] [ #24 ]
- [x] [cms_form_example](https://github.com/OCA/website-cms/tree/9.0/cms_form_example) [@simahawk] [ #24 ]
- [x] [cms_delete_content](https://github.com/OCA/website-cms/tree/9.0/cms_delete_content) [ @remytms] [ #27 ]

**Comment by ecino** [comment]
Should this be closed?

**Comment by simahawk** [comment]
@ecino oh yeah, tnx :)
