### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/website-cms#31]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] cms_delete_content - By @simahawk - #35 
- [x] cms_delete_content_example - By @simahawk - #35 
- [x] cms_form - By @simahawk - #36 
- [x] cms_form_example - By @simahawk - #36 
- [x] cms_status_message - By @simahawk - #35
- [x] cms_status_message_example - By @simahawk - #35

**Comment by emagdalenaC2i** [comment]
@pedrobaeza I think this issue could be closed
